# Generated by Django 6.0 on 2026-01-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='badge',
            field=models.CharField(blank=True, choices=[('popular', 'Popular'), ('premium', 'Premium'), ('new', 'New')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.TextField(help_text='Comma separated features'),
        ),
    ]
