# Generated by Django 6.0 on 2026-01-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_badge_alter_service_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Client / Recruiter / Mentor', max_length=150)),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
