# Generated by Django 6.0 on 2026-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class (e.g. fa-code, fa-comments)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
